// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../entities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class GetBoosterDto {
    "ID": string;
    "Name": string;
    "Description": string;
    "Category": entities$0.BoosterCategory;
    "Level": entities$0.BoosterLevel;
    "Platform": entities$0.Platform[];
    "Dependencies": string[];
    "Conflicts": string[];
    "Reversible": boolean;
    "RiskLevel": entities$0.RiskLevel;
    "Version": string;
    "IsApplied": boolean;
    "AppliedAt": time$0.Time | null;
    "RevertedAt": time$0.Time | null;
    "Tags": string[];

    /** Creates a new GetBoosterDto instance. */
    constructor($$source: Partial<GetBoosterDto> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Category" in $$source)) {
            this["Category"] = entities$0.BoosterCategory.$zero;
        }
        if (!("Level" in $$source)) {
            this["Level"] = entities$0.BoosterLevel.$zero;
        }
        if (!("Platform" in $$source)) {
            this["Platform"] = [];
        }
        if (!("Dependencies" in $$source)) {
            this["Dependencies"] = [];
        }
        if (!("Conflicts" in $$source)) {
            this["Conflicts"] = [];
        }
        if (!("Reversible" in $$source)) {
            this["Reversible"] = false;
        }
        if (!("RiskLevel" in $$source)) {
            this["RiskLevel"] = entities$0.RiskLevel.$zero;
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }
        if (!("IsApplied" in $$source)) {
            this["IsApplied"] = false;
        }
        if (!("AppliedAt" in $$source)) {
            this["AppliedAt"] = null;
        }
        if (!("RevertedAt" in $$source)) {
            this["RevertedAt"] = null;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetBoosterDto instance from a string or object.
     */
    static createFrom($$source: any = {}): GetBoosterDto {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField14_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Platform" in $$parsedSource) {
            $$parsedSource["Platform"] = $$createField5_0($$parsedSource["Platform"]);
        }
        if ("Dependencies" in $$parsedSource) {
            $$parsedSource["Dependencies"] = $$createField6_0($$parsedSource["Dependencies"]);
        }
        if ("Conflicts" in $$parsedSource) {
            $$parsedSource["Conflicts"] = $$createField7_0($$parsedSource["Conflicts"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField14_0($$parsedSource["Tags"]);
        }
        return new GetBoosterDto($$parsedSource as Partial<GetBoosterDto>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
