// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../core/domain/dto/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../../core/domain/entities/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as i18n$0 from "../../core/domain/services/i18n/models.js";

export function GetAvailableBoosters(lang: i18n$0.Language): $CancellablePromise<dto$0.BoosterDto[]> {
    return $Call.ByID(403465565, lang).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetBoostersByCategory(category: entities$0.BoosterCategory, lang: i18n$0.Language): $CancellablePromise<dto$0.BoosterDto[]> {
    return $Call.ByID(1321176637, category, lang).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetExecutionQueueState(): $CancellablePromise<entities$0.QueueState | null> {
    return $Call.ByID(2129142985).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetOperationsHistory(id: string): $CancellablePromise<entities$0.BoostOperation[] | null> {
    return $Call.ByID(3099803181, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function InitBoosterApply(id: string): $CancellablePromise<entities$0.InitResult> {
    return $Call.ByID(2277708641, id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function InitBoosterApplyBatch(ids: string[]): $CancellablePromise<entities$0.InitResult> {
    return $Call.ByID(1084139143, ids).then(($result: any) => {
        return $$createType7($result);
    });
}

export function InitRevertBooster(id: string): $CancellablePromise<entities$0.InitResult> {
    return $Call.ByID(261801925, id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function InitRevertBoosterBatch(ids: string[]): $CancellablePromise<entities$0.InitResult> {
    return $Call.ByID(3653132443, ids).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(285763924);
}

// Private type creation functions
const $$createType0 = dto$0.BoosterDto.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = entities$0.QueueState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = entities$0.BoostOperation.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = entities$0.InitResult.createFrom;
