// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../../core/domain/entities/models.js";

export function GetSystemMetrics(): $CancellablePromise<entities$0.SystemMetrics | null> {
    return $Call.ByID(436626668).then(($result: any) => {
        return $$createType1($result);
    });
}

export function IsMetrics(): $CancellablePromise<boolean> {
    return $Call.ByID(2022814087);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(265607945);
}

export function StartRealTimeMetrics(intervalSeconds: number): $CancellablePromise<void> {
    return $Call.ByID(3535171632, intervalSeconds);
}

export function StopRealTimeMetrics(): $CancellablePromise<void> {
    return $Call.ByID(1112413752);
}

// Private type creation functions
const $$createType0 = entities$0.SystemMetrics.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
