// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entities$0 from "../../core/domain/entities/models.js";

export function GetHardwareInfo(): $CancellablePromise<entities$0.SystemInfo | null> {
    return $Call.ByID(2886942096).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSystemInfo(): $CancellablePromise<entities$0.SystemInfo | null> {
    return $Call.ByID(2140658741).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RefreshSystemInfo(): $CancellablePromise<void> {
    return $Call.ByID(862252138);
}

export function SetContext(): $CancellablePromise<void> {
    return $Call.ByID(345278435);
}

// Private type creation functions
const $$createType0 = entities$0.SystemInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
