// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {context} from '../models';

export function ApplyBooster(arg1:string):Promise<entities.BoosterResult>;

export function ApplyBoosterBatch(arg1:Array<string>):Promise<entities.BatchResult>;

export function GetAvailableBoosters():Promise<Array<entities.Booster>>;

export function GetBoosterState(arg1:string):Promise<entities.BoosterState>;

export function GetBoostersByCategory(arg1:string):Promise<Array<entities.Booster>>;

export function RevertBooster(arg1:string):Promise<entities.BoosterResult>;

export function SetContext(arg1:context.Context):Promise<void>;
