// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {i18n} from '../models';
import {dto} from '../models';
import {context} from '../models';

export function ApplyBooster(arg1:string):Promise<entities.BoosterResult>;

export function ApplyBoosterBatch(arg1:Array<string>):Promise<entities.BatchResult>;

export function GetAvailableBoosters(arg1:i18n.Language):Promise<Array<dto.BoosterDto>>;

export function GetBoosterState(arg1:string):Promise<entities.BoosterRollbackState>;

export function GetBoostersByCategory(arg1:entities.BoosterCategory,arg2:i18n.Language):Promise<Array<dto.BoosterDto>>;

export function RevertBooster(arg1:string):Promise<entities.BoosterResult>;

export function SetContext(arg1:context.Context):Promise<void>;
