// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyBooster(arg1) {
  return window['go']['handlers']['BoosterHandler']['ApplyBooster'](arg1);
}

export function ApplyBoosterBatch(arg1) {
  return window['go']['handlers']['BoosterHandler']['ApplyBoosterBatch'](arg1);
}

export function GetAvailableBoosters() {
  return window['go']['handlers']['BoosterHandler']['GetAvailableBoosters']();
}

export function GetBoosterState(arg1) {
  return window['go']['handlers']['BoosterHandler']['GetBoosterState'](arg1);
}

export function GetBoostersByCategory(arg1) {
  return window['go']['handlers']['BoosterHandler']['GetBoostersByCategory'](arg1);
}

export function RevertBooster(arg1) {
  return window['go']['handlers']['BoosterHandler']['RevertBooster'](arg1);
}

export function SetContext(arg1) {
  return window['go']['handlers']['BoosterHandler']['SetContext'](arg1);
}
