// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemMetrics() {
  return window['go']['handlers']['MonitoringHandler']['GetSystemMetrics']();
}

export function IsMonitoring() {
  return window['go']['handlers']['MonitoringHandler']['IsMonitoring']();
}

export function SetContext(arg1) {
  return window['go']['handlers']['MonitoringHandler']['SetContext'](arg1);
}

export function StartRealTimeMonitoring(arg1) {
  return window['go']['handlers']['MonitoringHandler']['StartRealTimeMonitoring'](arg1);
}

export function StopRealTimeMonitoring() {
  return window['go']['handlers']['MonitoringHandler']['StopRealTimeMonitoring']();
}
