// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {context} from '../models';

export function GetSystemMetrics():Promise<entities.SystemMetrics>;

export function IsMonitoring():Promise<boolean>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartRealTimeMonitoring(arg1:number):Promise<void>;

export function StopRealTimeMonitoring():Promise<void>;
