// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {context} from '../models';

export function ApplyOptimization(arg1:string):Promise<entities.OptimizationResult>;

export function ApplyOptimizationBatch(arg1:Array<string>):Promise<entities.BatchResult>;

export function GetAvailableOptimizations():Promise<Array<entities.Optimization>>;

export function GetOptimizationState(arg1:string):Promise<entities.OptimizationState>;

export function GetOptimizationsByCategory(arg1:string):Promise<Array<entities.Optimization>>;

export function RevertOptimization(arg1:string):Promise<entities.OptimizationResult>;

export function SetContext(arg1:context.Context):Promise<void>;
