// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyOptimization(arg1) {
  return window['go']['handlers']['OptimizationHandler']['ApplyOptimization'](arg1);
}

export function ApplyOptimizationBatch(arg1) {
  return window['go']['handlers']['OptimizationHandler']['ApplyOptimizationBatch'](arg1);
}

export function GetAvailableOptimizations() {
  return window['go']['handlers']['OptimizationHandler']['GetAvailableOptimizations']();
}

export function GetOptimizationState(arg1) {
  return window['go']['handlers']['OptimizationHandler']['GetOptimizationState'](arg1);
}

export function GetOptimizationsByCategory(arg1) {
  return window['go']['handlers']['OptimizationHandler']['GetOptimizationsByCategory'](arg1);
}

export function RevertOptimization(arg1) {
  return window['go']['handlers']['OptimizationHandler']['RevertOptimization'](arg1);
}

export function SetContext(arg1) {
  return window['go']['handlers']['OptimizationHandler']['SetContext'](arg1);
}
