// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHardwareInfo() {
  return window['go']['handlers']['SystemHandler']['GetHardwareInfo']();
}

export function GetSystemInfo() {
  return window['go']['handlers']['SystemHandler']['GetSystemInfo']();
}

export function RefreshSystemInfo() {
  return window['go']['handlers']['SystemHandler']['RefreshSystemInfo']();
}

export function SetContext(arg1) {
  return window['go']['handlers']['SystemHandler']['SetContext'](arg1);
}
