// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {context} from '../models';

export function GetHardwareInfo():Promise<entities.SystemInfo>;

export function GetSystemInfo():Promise<entities.SystemInfo>;

export function RefreshSystemInfo():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
