// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A CancelFunc tells an operation to abandon its work.
 * A CancelFunc does not wait for the work to stop.
 * A CancelFunc may be called by multiple goroutines simultaneously.
 * After the first call, subsequent calls to a CancelFunc do nothing.
 */
export type CancelFunc = any;

/**
 * A Context carries a deadline, a cancellation signal, and other values across
 * API boundaries.
 * 
 * Context's methods may be called by multiple goroutines simultaneously.
 */
export type Context = any;
